### ISSUE TITLE
[CSX] BSUI error message - broken pipeline in collection environment

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/bluesky#1088]
````

[xf23id1@xf23id-ws3 ~/Users/2018/2018_08_Sandberg]$ bsui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/__init__.py", line 23, in <module>
    from .mca import EpicsMCA, EpicsDXP
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/mca.py", line 10, in <module>
    from .areadetector import EpicsSignalWithRBV as SignalWithRBV
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/areadetector/__init__.py", line 8, in <module>
    from .base import *
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/areadetector/base.py", line 6, in <module>
    import networkx as nx
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/generators/__init__.py", line 6, in <module>
    from networkx.generators.classic import *
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/generators/classic.py", line 26, in <module>
    from networkx.algorithms.bipartite.generators import complete_bipartite_graph
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/algorithms/__init__.py", line 58, in <module>
    import networkx.algorithms.community
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/algorithms/community/__init__.py", line 21, in <module>
    from networkx.algorithms.community.community_generators import *
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/networkx/algorithms/community/community_generators.py", line 20, in <module>
    from scipy.special import zeta as _zeta
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

Versions of DAMA software:

    - Bluesky    : v1.1.0
    - Ophyd      : v1.0.0
    - Databroker : v0.9.4

Links to Bluesky and Databroker tutorials:

    - http://nsls-ii.github.io/bluesky/tutorial.html
    - http://nsls-ii.github.io/databroker/tutorial.html

If you get lost or confused, then we want to know! We have a friendly chat channel:

    https://gitter.im/NSLS-II/DAMA

or you can file a bug to let us know where our documentation could be made more clear:

    https://github.com/NSLS-II/Bug-Reports/issues

bsui is running these commands now to start an interactive computing environment for data acquisition:
    $ conda activate collection-2018-1.0.1
    $ ipython --profile=collection 

Activating auto-logging. Current session state plus future input saved.
Filename       : /epics/xf/23id/ophyd/logs/xf23id1_log.py
Mode           : append
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: collection
Using matplotlib backend: Qt5Agg
Loading metadata history from /home/xf23id1/.config/bluesky/bluesky_history.db
/epics/xf/23id/ipython/profile_collection/startup/csx1/startup/__init__.py:4: PyGIWarning: Hkl was imported without specifying a version first. Use gi.require_version('Hkl', '5.0') before import to ensure that the right version gets loaded.
  from .endstation import *
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/suspenders.py:505: UserWarning: bluesky.suspenders.SuspendOutBand is deprecated.
  warn("bluesky.suspenders.SuspendOutBand is deprecated.")
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/device.py:738: UserWarning: 'signal_names' has been renamed 'component_names' for clarity because it may include a mixture of Signals and Devices -- any Components. This alias may be removed in a future release of ophyd.
  warnings.warn("'signal_names' has been renamed 'component_names' for "

In [1]: 


````

**Comment by danielballan** [comment]
```
BrokenPipeError: [Errno 32] Broken pipe
```

That's "broken pipe", a UNIX concept, not "broken pipeline," which people at NSLS-II use variously to mean "Jupyter notebook" or workflow generally

This sure looks like yet-another-symptom of lamentably unstable home directories. Closing as not actionable; bluesky has to assume that it is deployed on a working system.
