### ISSUE TITLE
Ship an optional utility that makes Tracebacks terser

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#870]
A common problem for novices using bluesky in IPython is that its tracebacks can be _very_ long (thanks to RunEngine + plan_mutator(s)). Novices don't usually figure out to "just scroll to the bottom".

Proposed Solution: We could use `excepthook` to display just the proximate error. We could write the full error to a tempfile and display the path of that file. This would be an opt-in utility that would have to be explicitly turned on (likely in IPython profiles), not something that bluesky would just do at import. But I do think it is a reasonable thing to ship in `bluesky.utils`.

**Comment by prjemian** [comment]
+1 for mind-reading

**Comment by danielballan** [comment]
IPython's built-in magic `%xmode` is a step in the right direction. We probably want to provide something even more aggressive. Demo:

<details>
```
In [17]: RE(123)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-aef0e1e0a5e6> in <module>()
----> 1 RE(123)

~/Documents/Repos/bluesky/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    715         self._metadata_per_call.update(metadata_kw)
    716
--> 717         gen = ensure_generator(plan)
    718         for wrapper_func in self.preprocessors:
    719             gen = wrapper_func(gen)

~/Documents/Repos/bluesky/bluesky/utils.py in ensure_generator(plan)
    112     if isinstance(plan, Msg):
    113         return single_gen(plan)
--> 114     gen = iter(plan)  # no-op on generators; needed for classes
    115     if not isinstance(gen, PLAN_TYPES):
    116         # If plan does not support .send, we must wrap it in a generator.

TypeError: 'int' object is not iterable

In [18]: %xmode plain
Exception reporting mode: Plain

In [19]: RE(123)
Traceback (most recent call last):
  File "<ipython-input-19-aef0e1e0a5e6>", line 1, in <module>
    RE(123)
  File "/Users/dallan/Documents/Repos/bluesky/bluesky/run_engine.py", line 717, in __call__
    gen = ensure_generator(plan)
  File "/Users/dallan/Documents/Repos/bluesky/bluesky/utils.py", line 114, in ensure_generator
    gen = iter(plan)  # no-op on generators; needed for classes
TypeError: 'int' object is not iterable
```
</details>

**Comment by danielballan** [comment]
We should also look at: https://vorpus.org/blog/beautiful-tracebacks-in-trio-v070/

**Comment by stan-dot** [comment]
trio does not seem to be a dependency of the project anymore.

closely connected to 
- https://github.com/DiamondLightSource/blueapi/issues/489
- https://github.com/bluesky/bluesky/issues/1274
